name: Main workflow

on:
    push:
        branches:
            - main
        paths:
            - "src/*"
            - "**.json"
            - "**.html"

jobs:
    get_version:
        name: Retrieve version
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.package_version.outputs.version }}
        steps:
            - uses: actions/checkout@v6

            - name: Get Package version
              id: package_version
              run: |
                  echo "Reading package.json"
                  PACKAGE_VERSION=$(cat ./package.json | jq '.version' | tr -d '"')
                  echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT

    create-release:
        name: Create pre-release
        runs-on: ubuntu-latest
        needs:
            - get_version
        env:
            VERSION: ${{ needs.get_version.outputs.version }}
            GH_TOKEN: ${{ github.token }}
        steps:
            - name: Create pre-release
              run: |
                  gh release create ${{ env.VERSION }} -R '${{ github.repository }}' --prerelease --generate-notes

    todo:
        name: todo
        runs-on: ubuntu-latest
        steps:
            - uses: "actions/checkout@v6"

            - name: "TODO to Issue"
              uses: "alstr/todo-to-issue-action@v5"
